FROM python:3.12-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/frontend/ app/frontend/
COPY src/ src/
COPY data/ data/

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "app/frontend/home.py"]
