FROM python:3.12-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/backend/ app/backend/
COPY src/ src/
COPY models/ models/

EXPOSE 5000

CMD ["python", "-m", "app.backend.main"]
